/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const Wrapper = styled.div`
  position: relative;
  top: 40%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 5rem;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>I'm Ian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>현재 페이지 개발 중입니다.</Wrapper>
    </>
  );
};

export default Home;
